org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Fabric (https://fabricmc.net/develop)
minecraft_version=26.1.2
loader_version=0.19.3

# Mod Properties
mod_version=1.14.0-26.1.2
maven_group=dev.stardust
archives_base_name=stardust

# Meteor (https://maven.meteordev.org)
meteor_version=26.1.2-SNAPSHOT

# XaeroMinimap / XaeroWorldMap（26.1.2 版）
xaeros_minimap_version=fabric-26.1.2-26.5.0
xaeros_worldmap_version=fabric-26.1.2-1.46.0
